// SEO Metadata Configuration
// Auto-generated by Agent 9

export const seoConfig = {
  "siteName": "Haywood Universal",
  "siteUrl": "https://haywooduniversal.com",
  "defaultTitle": "Haywood Universal - Professional Services",
  "defaultDescription": "Professional painting, remodeling, and property management services. Quality workmanship and exceptional customer service.",
  "keywords": [
    "painting services",
    "home remodeling",
    "property management",
    "interior painting",
    "exterior painting",
    "kitchen remodeling",
    "bathroom remodeling",
    "rental management"
  ],
  "author": "Haywood Universal",
  "ogImage": "https://haywooduniversal.com/images/og-image.jpg",
  "twitterCard": "summary_large_image",
  "themeColor": "#2563eb",
  "pages": {
    "/": {
      "title": "Haywood Universal - Professional Painting & Remodeling",
      "description": "Professional painting, remodeling, and property management services. Transform your space with quality workmanship."
    },
    "/services": {
      "title": "Our Services - Haywood Universal",
      "description": "Comprehensive painting, remodeling, and property management services. Interior, exterior, and commercial solutions."
    },
    "/gallery": {
      "title": "Project Gallery - Haywood Universal",
      "description": "Browse our portfolio of completed projects. See the quality and craftsmanship that sets us apart."
    },
    "/contact": {
      "title": "Contact Us - Haywood Universal",
      "description": "Get in touch for a free consultation and quote. Professional service you can trust."
    },
    "/project-management": {
      "title": "Project Management - Haywood Universal",
      "description": "End-to-end project management ensuring on-time, within-budget completion. Professional execution guaranteed."
    },
    "/rooms-for-rent": {
      "title": "Rooms for Rent - Haywood Universal",
      "description": "Quality rooms for rent in safe neighborhoods. Affordable, clean, and well-maintained accommodations."
    }
  }
};

export function getPageMeta(path: string) {
  const pageMeta = seoConfig.pages[path as keyof typeof seoConfig.pages];
  
  return {
    title: pageMeta?.title || seoConfig.defaultTitle,
    description: pageMeta?.description || seoConfig.defaultDescription,
    keywords: seoConfig.keywords.join(', '),
    openGraph: {
      title: pageMeta?.title || seoConfig.defaultTitle,
      description: pageMeta?.description || seoConfig.defaultDescription,
      url: `${seoConfig.siteUrl}${path}`,
      siteName: seoConfig.siteName,
      images: [{ url: seoConfig.ogImage }],
      type: 'website',
    },
    twitter: {
      card: seoConfig.twitterCard,
      title: pageMeta?.title || seoConfig.defaultTitle,
      description: pageMeta?.description || seoConfig.defaultDescription,
      images: [seoConfig.ogImage],
    },
  };
}
