// Structured Data (JSON-LD) for SEO
// Auto-generated by Agent 9

export const structuredData = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  "name": "Haywood Universal",
  "image": "https://haywooduniversal.com/images/logo.jpg",
  "@id": "https://haywooduniversal.com",
  "url": "https://haywooduniversal.com",
  "telephone": "(123) 456-7890",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "123 Main Street",
    "addressLocality": "Your City",
    "addressRegion": "ST",
    "postalCode": "12345",
    "addressCountry": "US"
  },
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": 40.7128,
    "longitude": -74.006
  },
  "openingHoursSpecification": [
    {
      "@type": "OpeningHoursSpecification",
      "dayOfWeek": [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
      ],
      "opens": "08:00",
      "closes": "18:00"
    },
    {
      "@type": "OpeningHoursSpecification",
      "dayOfWeek": "Saturday",
      "opens": "09:00",
      "closes": "16:00"
    }
  ],
  "sameAs": [
    "https://facebook.com/haywooduniversal",
    "https://instagram.com/haywooduniversal"
  ],
  "priceRange": "$$",
  "areaServed": {
    "@type": "GeoCircle",
    "geoMidpoint": {
      "@type": "GeoCoordinates",
      "latitude": 40.7128,
      "longitude": -74.006
    },
    "geoRadius": "50 miles"
  },
  "hasOfferCatalog": {
    "@type": "OfferCatalog",
    "name": "Services",
    "itemListElement": [
      {
        "@type": "Offer",
        "itemOffered": {
          "@type": "Service",
          "name": "Professional Painting",
          "description": "Interior and exterior painting services"
        }
      },
      {
        "@type": "Offer",
        "itemOffered": {
          "@type": "Service",
          "name": "Home Remodeling",
          "description": "Kitchen and bathroom remodeling"
        }
      },
      {
        "@type": "Offer",
        "itemOffered": {
          "@type": "Service",
          "name": "Property Management",
          "description": "Comprehensive rental property management"
        }
      }
    ]
  }
};

export function getStructuredData() {
  return JSON.stringify(structuredData);
}
