name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20.x'

jobs:
  # Linting and Type Checking
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./nextjs-app

      - name: Run ESLint
        run: npm run lint
        working-directory: ./nextjs-app

      - name: Run TypeScript type check
        run: npm run type-check
        working-directory: ./nextjs-app

      - name: Run Prettier check
        run: npx prettier --check "**/*.{ts,tsx,md,json}"
        working-directory: ./nextjs-app

  # Unit Tests
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./nextjs-app

      - name: Run unit tests
        run: npm run test
        working-directory: ./nextjs-app

      - name: Generate coverage report
        run: npm run test:coverage
        working-directory: ./nextjs-app

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./nextjs-app/coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella

  # Build Verification
  build:
    name: Build Verification
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./nextjs-app

      - name: Build application
        run: npm run build
        working-directory: ./nextjs-app

      - name: Check bundle size
        run: |
          BUNDLE_SIZE=$(du -sk .next/static | cut -f1)
          echo "Bundle size: ${BUNDLE_SIZE}KB"
          if [ $BUNDLE_SIZE -gt 150000 ]; then
            echo "::error::Bundle size exceeds 150MB limit"
            exit 1
          fi
        working-directory: ./nextjs-app

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: nextjs-app/.next
          retention-days: 7

  # E2E Tests
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./nextjs-app

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./nextjs-app

      - name: Run E2E tests
        run: npm run test:e2e
        working-directory: ./nextjs-app
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: nextjs-app/playwright-report
          retention-days: 30

  # Agent Tests
  agent-tests:
    name: Agent Pipeline Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install agent dependencies
        run: npm ci
        working-directory: ./agents/agent-${{ matrix.agent }}-*/

      - name: Run agent tests
        run: npm test
        working-directory: ./agents/agent-${{ matrix.agent }}-*/

  # Security Scan
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        working-directory: ./nextjs-app
        continue-on-error: true

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # Accessibility Tests
  accessibility:
    name: Accessibility Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./nextjs-app

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: nextjs-app/.next

      - name: Start Next.js server
        run: npm start &
        working-directory: ./nextjs-app
        env:
          PORT: 3000

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run Pa11y accessibility tests
        run: |
          npm install -g pa11y-ci
          pa11y-ci --config .pa11yci.json

  # Lighthouse Performance
  lighthouse:
    name: Lighthouse Performance
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./nextjs-app

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: nextjs-app/.next

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './nextjs-app/.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

  # Database Tests
  database:
    name: Database Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./nextjs-app

      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        working-directory: ./nextjs-app
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/testdb

      - name: Run database tests
        run: npm run test:db
        working-directory: ./nextjs-app
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/testdb

  # Summary
  ci-success:
    name: CI Pipeline Success
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, build, e2e-tests, agent-tests, security, accessibility, lighthouse, database]
    if: success()
    steps:
      - name: Success message
        run: |
          echo "✅ All CI checks passed successfully!"
          echo "Ready for code review and merge."
