import fs from 'fs-extra';
import path from 'path';

class PerformanceOptimizer {
  private outputDir: string;
  private configDir: string;

  constructor() {
    this.outputDir = path.join(process.cwd(), '../../');
    this.configDir = this.outputDir;
  }

  async build() {
    console.log('⚡ Building performance optimization files...\n');

    // Create performance configs
    await this.createNextConfig();
    await this.createVercelConfig();
    await this.createLighthouseConfig();
    await this.createPerformanceUtils();

    console.log('\n✅ Performance optimization complete!');
    console.log(`📁 Output: ${this.configDir}`);
  }

  async createNextConfig() {
    const content = `/** @type {import('next').NextConfig} */
const nextConfig = {
  // Performance Optimizations
  reactStrictMode: true,
  swcMinify: true,
  
  // Image Optimization
  images: {
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 60,
    domains: ['haywooduniversal.com'],
  },

  // Compression
  compress: true,

  // Headers for caching and security
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          {
            key: 'X-DNS-Prefetch-Control',
            value: 'on',
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN',
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block',
          },
        ],
      },
      {
        source: '/images/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable',
          },
        ],
      },
      {
        source: '/_next/static/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable',
          },
        ],
      },
    ];
  },

  // Build optimizations
  experimental: {
    optimizeCss: true,
  },

  // Production source maps (disable for smaller bundles)
  productionBrowserSourceMaps: false,
};

module.exports = nextConfig;
`;

    await fs.writeFile(path.join(this.configDir, 'next.config.js'), content);
    console.log('  ✅ next.config.js created');
  }

  async createVercelConfig() {
    const content = `{
  "buildCommand": "npm run build",
  "outputDirectory": ".next",
  "devCommand": "npm run dev",
  "installCommand": "npm install",
  "framework": "nextjs",
  "regions": ["iad1"],
  "headers": [
    {
      "source": "/images/(.*)",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "public, max-age=31536000, immutable"
        }
      ]
    }
  ],
  "rewrites": [],
  "redirects": [],
  "cleanUrls": true,
  "trailingSlash": false
}
`;

    await fs.writeFile(path.join(this.configDir, 'vercel.json'), content);
    console.log('  ✅ vercel.json created');
  }

  async createLighthouseConfig() {
    const content = `module.exports = {
  ci: {
    collect: {
      numberOfRuns: 3,
      startServerCommand: 'npm run start',
      url: [
        'http://localhost:3000/',
        'http://localhost:3000/services',
        'http://localhost:3000/gallery',
        'http://localhost:3000/contact',
      ],
    },
    assert: {
      assertions: {
        'categories:performance': ['error', { minScore: 0.9 }],
        'categories:accessibility': ['error', { minScore: 0.9 }],
        'categories:best-practices': ['error', { minScore: 0.9 }],
        'categories:seo': ['error', { minScore: 0.9 }],
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
};
`;

    await fs.writeFile(path.join(this.configDir, 'lighthouserc.js'), content);
    console.log('  ✅ lighthouserc.js created');
  }

  async createPerformanceUtils() {
    const dir = path.join(this.configDir, 'lib');
    await fs.ensureDir(dir);

    const content = `// Performance Utilities
// Auto-generated by Agent 10

// Lazy load images with Intersection Observer
export function lazyLoadImages() {
  if (typeof window === 'undefined') return;

  const images = document.querySelectorAll('img[data-src]');
  
  const imageObserver = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        const img = entry.target as HTMLImageElement;
        const src = img.dataset.src;
        if (src) {
          img.src = src;
          img.removeAttribute('data-src');
          imageObserver.unobserve(img);
        }
      }
    });
  });

  images.forEach((img) => imageObserver.observe(img));
}

// Preload critical resources
export function preloadCriticalAssets() {
  if (typeof window === 'undefined') return;

  const criticalFonts = [
    '/fonts/inter-var.woff2',
  ];

  criticalFonts.forEach((font) => {
    const link = document.createElement('link');
    link.rel = 'preload';
    link.as = 'font';
    link.type = 'font/woff2';
    link.crossOrigin = 'anonymous';
    link.href = font;
    document.head.appendChild(link);
  });
}

// Measure Web Vitals
export function reportWebVitals(metric: any) {
  if (typeof window === 'undefined') return;

  // Log to console in development
  if (process.env.NODE_ENV === 'development') {
    console.log(metric);
  }

  // Send to analytics in production
  if (process.env.NODE_ENV === 'production') {
    // Example: Send to Google Analytics
    // window.gtag?.('event', metric.name, {
    //   value: Math.round(metric.value),
    //   event_label: metric.id,
    //   non_interaction: true,
    // });
  }
}

// Prefetch links on hover
export function prefetchOnHover() {
  if (typeof window === 'undefined') return;

  const links = document.querySelectorAll('a[href^="/"]');
  
  links.forEach((link) => {
    link.addEventListener('mouseenter', () => {
      const href = link.getAttribute('href');
      if (href) {
        const prefetchLink = document.createElement('link');
        prefetchLink.rel = 'prefetch';
        prefetchLink.href = href;
        document.head.appendChild(prefetchLink);
      }
    });
  });
}

// Debounce function for performance
export function debounce<T extends (...args: any[]) => any>(
  func: T,
  wait: number
): (...args: Parameters<T>) => void {
  let timeout: NodeJS.Timeout;
  
  return function executedFunction(...args: Parameters<T>) {
    const later = () => {
      clearTimeout(timeout);
      func(...args);
    };
    
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };
}

// Throttle function for performance
export function throttle<T extends (...args: any[]) => any>(
  func: T,
  limit: number
): (...args: Parameters<T>) => void {
  let inThrottle: boolean;
  
  return function executedFunction(...args: Parameters<T>) {
    if (!inThrottle) {
      func(...args);
      inThrottle = true;
      setTimeout(() => (inThrottle = false), limit);
    }
  };
}
`;

    await fs.writeFile(path.join(dir, 'performance.ts'), content);
    console.log('  ✅ Performance utilities created');
  }
}

// Execute
const optimizer = new PerformanceOptimizer();
optimizer.build().catch(console.error);
